name: use_case_generator
description: A CLI tool to automatically generate UseCase classes from Repository interfaces
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  dartz: ^0.10.1
dev_dependencies:
  test: ^1.24.0

executables:
  use_case_generator: